<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="4307" started-at="2017-11-17T17:40:52Z" finished-at="2017-11-17T17:40:56Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="4307" started-at="2017-11-17T17:40:52Z" finished-at="2017-11-17T17:40:56Z">
      <class name="plivo.com.test.SendMessage">
        <test-method status="PASS" signature="sendMessageTest([Ljava.lang.String;)[pri:0, instance:plivo.com.test.SendMessage@3e694b3f]" name="sendMessageTest" duration-ms="4276" started-at="2017-11-17T23:10:52Z" data-provider="getData" finished-at="2017-11-17T23:10:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@1494b84d]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- sendMessageTest -->
      </class> <!-- plivo.com.test.SendMessage -->
      <class name="plivo.com.test.GetMessage">
        <test-method status="FAIL" signature="getMessageTest([Ljava.lang.String;)[pri:0, instance:plivo.com.test.GetMessage@41d477ed]" name="getMessageTest" duration-ms="2" started-at="2017-11-17T23:10:56Z" data-provider="getData" finished-at="2017-11-17T23:10:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[Ljava.lang.String;@bc57b40]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at plivo.com.test.GetMessage.getMessageTest(GetMessage.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:669)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:877)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1201)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:776)
	at org.testng.TestRunner.run(TestRunner.java:634)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:425)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:420)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:385)
	at org.testng.SuiteRunner.run(SuiteRunner.java:334)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1318)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1243)
	at org.testng.TestNG.runSuites(TestNG.java:1161)
	at org.testng.TestNG.run(TestNG.java:1129)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getMessageTest -->
      </class> <!-- plivo.com.test.GetMessage -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
